---
# OS-dependent variables
mysql_service_name: "{{ 'mysql' if ansible_os_family == 'Debian' else 'mysqld' }}"
mysql_socket_path: "{{ '/var/run/mysqld/mysqld.sock' if ansible_os_family == 'Debian' else '/var/lib/mysql/mysql.sock' }}"
mysql_conf_dir: "{{ '/etc/mysql/conf.d' if ansible_os_family == 'Debian' else '/etc/my.cnf.d' }}"
